
spring:
  application:
    name: main-menu-service
server:
  port: 8001
  error:
    whitelabel:
      enabled: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/


